2800 #!/usr/bin/perl -w
2801 
2802 # Generate vectors.S, the trap/interrupt entry points.
2803 # There has to be one entry point per interrupt number
2804 # since otherwise there's no way for trap() to discover
2805 # the interrupt number.
2806 
2807 print "# generated by vectors.pl - do not edit\n";
2808 print "# handlers\n";
2809 print ".globl alltraps\n";
2810 for(my $i = 0; $i < 256; $i++){
2811     print ".globl vector$i\n";
2812     print "vector$i:\n";
2813     if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
2814         print "  pushl \$0\n";
2815     }
2816     print "  pushl \$$i\n";
2817     print "  jmp alltraps\n";
2818 }
2819 
2820 print "\n# vector table\n";
2821 print ".data\n";
2822 print ".globl vectors\n";
2823 print "vectors:\n";
2824 for(my $i = 0; $i < 256; $i++){
2825     print "  .long vector$i\n";
2826 }
2827 
2828 # sample output:
2829 #   # handlers
2830 #   .globl alltraps
2831 #   .globl vector0
2832 #   vector0:
2833 #     pushl $0
2834 #     pushl $0
2835 #     jmp alltraps
2836 #   ...
2837 #
2838 #   # vector table
2839 #   .data
2840 #   .globl vectors
2841 #   vectors:
2842 #     .long vector0
2843 #     .long vector1
2844 #     .long vector2
2845 #   ...
2846 
2847 
2848 
2849 
